### ISSUE TITLE
Links and extras articles

### ISSUE THREAD

**Issue by geidsonc** [Gabrielr2508/awesome-career-paths#1]
Hello, what the best way to include links and extras articles?
1. Include new section un README.md
2. New file with section division by topic content.

Ex: There this article of Annelise Grip that explain about Competencies Map and Career. [https://annelisegripp.com.br/mapa-de-competencias/](https://annelisegripp.com.br/mapa-de-competencias/). It is in Portuguese. Is it relevant for here? Take a look.

**Comment by gab0gomes** [comment]
Hi,

I think this should be an extra section, something like "Other career paths resources" as **Other Engineering Ladder Resources** in [Engineering Ladders](https://github.com/bmoeskau/engineering-ladders).

Could you submit a PR, please?

**Comment by geidsonc** [comment]
Great!! I'll submit the PR as soon a possible.
